server:
  port: 8765

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WCFApplication
    username: root
    password: #######
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
